### ISSUE TITLE
AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?

### ISSUE THREAD

**Issue by EdwinDNavarroMonserrat** [zreitz/multismash#15]
I get the following error when doing a dry-run :

Traceback (most recent call last):
  File "/users/PZS1114/navarromonserrat/.conda/envs/antismash/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/users/PZS1114/navarromonserrat/.conda/envs/antismash/lib/python3.10/site-packages/snakemake/__init__.py", line 2736, in main
    parser = get_argument_parser()
  File "/users/PZS1114/navarromonserrat/.conda/envs/antismash/lib/python3.10/site-packages/snakemake/__init__.py", line 1607, in get_argument_parser
    lp_solvers = pulp.list_solvers(onlyAvailable=True)
AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?

**Comment by zreitz** [comment]
Thanks for the report. I think this is a [snakemake issue](https://github.com/snakemake/snakemake/issues/2607).

Please downgrade pulp to 2.7.0 and try again
`conda install pulp=2.7.0` or `mamba install pulp=2.7.0`

**Comment by zreitz** [comment]
Hi, did this fix work for you?

**Comment by EdwinDNavarroMonserrat** [comment]
Yes!  Thanks for the help. Sorry for the late response.

**Comment by zreitz** [comment]
No problem, thanks for the update. I've adjusted the installation.
