### ISSUE TITLE
error in example workflow

### ISSUE THREAD

**Issue by waltercostamb** [zreitz/multismash#17]
Hello, 

I installed antiSMASH and multiSMASH:

```
$multismash -h
usage: multismash [-h] configfile [--cores CORES] [...]

multiSMASH is a Snakemake-based antiSMASH wrapper that streamlines 
large-scale analyses of BGCs across multiple genomes.

positional arguments:
  configfile  path to the YAML file with job configurations

optional arguments:
  -h, --help  show this help message and exit

Any additional arguments will be passed to Snakemake. Use `snakemake -h`
to see all available parameters. Flags you may find useful:
  --dry-run, -n   Do not execute anything, and display what would be done
  --quiet, -q     Do not output any progress or rule information
  --forceall, -F  Force the (re-)execution of all rules 
```

When I try the example, I get the error below, which I do not understand. Could you help me with this please?

```
$multismash example/config-example.yaml -n
Traceback (most recent call last):
  File "/tools/miniconda3_2024/envs/antismash_v7/bin/multismash", line 33, in <module>
    sys.exit(load_entry_point('multiSMASH', 'console_scripts', 'multismash')())
  File "/tools/multismash/multismash/multismash/main.py", line 69, in main
    configs = yaml.safe_load(yml)
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/tools/miniconda3_2024/envs/antismash_v7/lib/python3.9/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "example/config-example.yaml", line 213, column 75
```

**Comment by zreitz** [comment]
Hi, thanks for trying multiSMASH. 

```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "example/config-example.yaml", line 213, column 75`
  ```
  
This error generally means the config file is misformatted, but [the example](https://github.com/zreitz/multismash/blob/master/example/config-example.yaml) doesn't have a line 213.
Have you edit the file?

**Comment by waltercostamb** [comment]
The file was indeed malformatted. Thank you!
